  
it:
	javac Tester.java 


test:
	javac Tester.java 
	java Tester add
	java Tester term
	java Tester poly


clean:
	/bin/rm *class


print:
	a2ps --delegate=no -T 4 -q -Avirtual -2 -L 70 -o xd FIX ME


